### ISSUE TITLE
incorrect bindaddress?

### ISSUE THREAD

**Issue by r3k2** [42wim/matterstuff#3]
hello... this is not working for me for some reason.. prob something silly. can you check please?

```
GoLang]$ uptime | bin/mattertee 
2016/07/16 03:37:09 incorrect bindaddress
```

why incorrect bind address?
I setup a config on my home dir
and added the webhookid etc..

**Comment by 42wim** [comment]
Could you do a `go get -u github.com/42wim/matterstuff/mattertee` and rebuild ?
The matterhook library had a bug, fixed now.

**Comment by r3k2** [comment]
working good now.. thanks!
